/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/DroppedItem.def
	public class EntityBaseEntityCall_DroppedItemBase : EntityCall
	{

		public EntityBaseEntityCall_DroppedItemBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_DroppedItemBase : EntityCall
	{

		public EntityCellEntityCall_DroppedItemBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void pickUpRequest()
		{
			Bundle pBundle = newCall("pickUpRequest", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}
	}
