/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			List<DATATYPE_BASE> pAccount_onCreateAvatarResult_args = new List<DATATYPE_BASE>();
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[24]);

			Method pAccount_onCreateAvatarResult = new Method();
			pAccount_onCreateAvatarResult.name = "onCreateAvatarResult";
			pAccount_onCreateAvatarResult.methodUtype = 6;
			pAccount_onCreateAvatarResult.aliasID = 1;
			pAccount_onCreateAvatarResult.args = pAccount_onCreateAvatarResult_args;

			pAccountModule.methods["onCreateAvatarResult"] = pAccount_onCreateAvatarResult; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onCreateAvatarResult.aliasID] = pAccount_onCreateAvatarResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onCreateAvatarResult / 6).");

			List<DATATYPE_BASE> pAccount_onRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onRemoveAvatar_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onRemoveAvatar = new Method();
			pAccount_onRemoveAvatar.name = "onRemoveAvatar";
			pAccount_onRemoveAvatar.methodUtype = 7;
			pAccount_onRemoveAvatar.aliasID = 2;
			pAccount_onRemoveAvatar.args = pAccount_onRemoveAvatar_args;

			pAccountModule.methods["onRemoveAvatar"] = pAccount_onRemoveAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onRemoveAvatar.aliasID] = pAccount_onRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onRemoveAvatar / 7).");

			List<DATATYPE_BASE> pAccount_onReqAvatarList_args = new List<DATATYPE_BASE>();
			pAccount_onReqAvatarList_args.Add(EntityDef.id2datatypes[25]);

			Method pAccount_onReqAvatarList = new Method();
			pAccount_onReqAvatarList.name = "onReqAvatarList";
			pAccount_onReqAvatarList.methodUtype = 5;
			pAccount_onReqAvatarList.aliasID = 3;
			pAccount_onReqAvatarList.args = pAccount_onReqAvatarList_args;

			pAccountModule.methods["onReqAvatarList"] = pAccount_onReqAvatarList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqAvatarList.aliasID] = pAccount_onReqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqAvatarList / 5).");

			List<DATATYPE_BASE> pAccount_reqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqAvatarList = new Method();
			pAccount_reqAvatarList.name = "reqAvatarList";
			pAccount_reqAvatarList.methodUtype = 1;
			pAccount_reqAvatarList.aliasID = -1;
			pAccount_reqAvatarList.args = pAccount_reqAvatarList_args;

			pAccountModule.methods["reqAvatarList"] = pAccount_reqAvatarList; 
			pAccountModule.base_methods["reqAvatarList"] = pAccount_reqAvatarList;

			pAccountModule.idbase_methods[pAccount_reqAvatarList.methodUtype] = pAccount_reqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarList / 1).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 2;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 2).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqRemoveAvatar = new Method();
			pAccount_reqRemoveAvatar.name = "reqRemoveAvatar";
			pAccount_reqRemoveAvatar.methodUtype = 3;
			pAccount_reqRemoveAvatar.aliasID = -1;
			pAccount_reqRemoveAvatar.args = pAccount_reqRemoveAvatar_args;

			pAccountModule.methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar; 
			pAccountModule.base_methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatar.methodUtype] = pAccount_reqRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatar / 3).");

			List<DATATYPE_BASE> pAccount_selectAvatarGame_args = new List<DATATYPE_BASE>();
			pAccount_selectAvatarGame_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_selectAvatarGame = new Method();
			pAccount_selectAvatarGame.name = "selectAvatarGame";
			pAccount_selectAvatarGame.methodUtype = 4;
			pAccount_selectAvatarGame.aliasID = -1;
			pAccount_selectAvatarGame.args = pAccount_selectAvatarGame_args;

			pAccountModule.methods["selectAvatarGame"] = pAccount_selectAvatarGame; 
			pAccountModule.base_methods["selectAvatarGame"] = pAccount_selectAvatarGame;

			pAccountModule.idbase_methods[pAccount_selectAvatarGame.methodUtype] = pAccount_selectAvatarGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(selectAvatarGame / 4).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_HP = new Property();
			pAvatar_HP.name = "HP";
			pAvatar_HP.properUtype = 47001;
			pAvatar_HP.properFlags = 4;
			pAvatar_HP.aliasID = 4;
			Int32 Avatar_HP_defval;
			Int32.TryParse("0", out Avatar_HP_defval);
			pAvatar_HP.defaultVal = Avatar_HP_defval;
			pAvatarModule.propertys["HP"] = pAvatar_HP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP.aliasID] = pAvatar_HP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP / 47001).");

			Property pAvatar_HP_Max = new Property();
			pAvatar_HP_Max.name = "HP_Max";
			pAvatar_HP_Max.properUtype = 47002;
			pAvatar_HP_Max.properFlags = 4;
			pAvatar_HP_Max.aliasID = 5;
			Int32 Avatar_HP_Max_defval;
			Int32.TryParse("0", out Avatar_HP_Max_defval);
			pAvatar_HP_Max.defaultVal = Avatar_HP_Max_defval;
			pAvatarModule.propertys["HP_Max"] = pAvatar_HP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP_Max.aliasID] = pAvatar_HP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP_Max / 47002).");

			Property pAvatar_MP = new Property();
			pAvatar_MP.name = "MP";
			pAvatar_MP.properUtype = 47003;
			pAvatar_MP.properFlags = 4;
			pAvatar_MP.aliasID = 6;
			Int32 Avatar_MP_defval;
			Int32.TryParse("0", out Avatar_MP_defval);
			pAvatar_MP.defaultVal = Avatar_MP_defval;
			pAvatarModule.propertys["MP"] = pAvatar_MP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP.aliasID] = pAvatar_MP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP / 47003).");

			Property pAvatar_MP_Max = new Property();
			pAvatar_MP_Max.name = "MP_Max";
			pAvatar_MP_Max.properUtype = 47004;
			pAvatar_MP_Max.properFlags = 4;
			pAvatar_MP_Max.aliasID = 7;
			Int32 Avatar_MP_Max_defval;
			Int32.TryParse("0", out Avatar_MP_Max_defval);
			pAvatar_MP_Max.defaultVal = Avatar_MP_Max_defval;
			pAvatarModule.propertys["MP_Max"] = pAvatar_MP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP_Max.aliasID] = pAvatar_MP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP_Max / 47004).");

			Property pAvatar_attack_Max = new Property();
			pAvatar_attack_Max.name = "attack_Max";
			pAvatar_attack_Max.properUtype = 17;
			pAvatar_attack_Max.properFlags = 16;
			pAvatar_attack_Max.aliasID = 8;
			Int32 Avatar_attack_Max_defval;
			Int32.TryParse("10", out Avatar_attack_Max_defval);
			pAvatar_attack_Max.defaultVal = Avatar_attack_Max_defval;
			pAvatarModule.propertys["attack_Max"] = pAvatar_attack_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_attack_Max.aliasID] = pAvatar_attack_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(attack_Max / 17).");

			Property pAvatar_attack_Min = new Property();
			pAvatar_attack_Min.name = "attack_Min";
			pAvatar_attack_Min.properUtype = 18;
			pAvatar_attack_Min.properFlags = 16;
			pAvatar_attack_Min.aliasID = 9;
			Int32 Avatar_attack_Min_defval;
			Int32.TryParse("0", out Avatar_attack_Min_defval);
			pAvatar_attack_Min.defaultVal = Avatar_attack_Min_defval;
			pAvatarModule.propertys["attack_Min"] = pAvatar_attack_Min; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_attack_Min.aliasID] = pAvatar_attack_Min;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(attack_Min / 18).");

			Property pAvatar_defence = new Property();
			pAvatar_defence.name = "defence";
			pAvatar_defence.properUtype = 19;
			pAvatar_defence.properFlags = 16;
			pAvatar_defence.aliasID = 10;
			Int32 Avatar_defence_defval;
			Int32.TryParse("0", out Avatar_defence_defval);
			pAvatar_defence.defaultVal = Avatar_defence_defval;
			pAvatarModule.propertys["defence"] = pAvatar_defence; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_defence.aliasID] = pAvatar_defence;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(defence / 19).");

			Property pAvatar_dexterity = new Property();
			pAvatar_dexterity.name = "dexterity";
			pAvatar_dexterity.properUtype = 25;
			pAvatar_dexterity.properFlags = 16;
			pAvatar_dexterity.aliasID = 11;
			Int32 Avatar_dexterity_defval;
			Int32.TryParse("", out Avatar_dexterity_defval);
			pAvatar_dexterity.defaultVal = Avatar_dexterity_defval;
			pAvatarModule.propertys["dexterity"] = pAvatar_dexterity; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_dexterity.aliasID] = pAvatar_dexterity;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(dexterity / 25).");

			Property pAvatar_dodge = new Property();
			pAvatar_dodge.name = "dodge";
			pAvatar_dodge.properUtype = 21;
			pAvatar_dodge.properFlags = 16;
			pAvatar_dodge.aliasID = 12;
			Int32 Avatar_dodge_defval;
			Int32.TryParse("0", out Avatar_dodge_defval);
			pAvatar_dodge.defaultVal = Avatar_dodge_defval;
			pAvatarModule.propertys["dodge"] = pAvatar_dodge; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_dodge.aliasID] = pAvatar_dodge;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(dodge / 21).");

			Property pAvatar_equipItemList = new Property();
			pAvatar_equipItemList.name = "equipItemList";
			pAvatar_equipItemList.properUtype = 7;
			pAvatar_equipItemList.properFlags = 32;
			pAvatar_equipItemList.aliasID = 13;
			pAvatar_equipItemList.defaultVal = EntityDef.id2datatypes[28].parseDefaultValStr("");
			pAvatarModule.propertys["equipItemList"] = pAvatar_equipItemList; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_equipItemList.aliasID] = pAvatar_equipItemList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(equipItemList / 7).");

			Property pAvatar_equipWeapon = new Property();
			pAvatar_equipWeapon.name = "equipWeapon";
			pAvatar_equipWeapon.properUtype = 8;
			pAvatar_equipWeapon.properFlags = 4;
			pAvatar_equipWeapon.aliasID = 14;
			Int32 Avatar_equipWeapon_defval;
			Int32.TryParse("-1", out Avatar_equipWeapon_defval);
			pAvatar_equipWeapon.defaultVal = Avatar_equipWeapon_defval;
			pAvatarModule.propertys["equipWeapon"] = pAvatar_equipWeapon; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_equipWeapon.aliasID] = pAvatar_equipWeapon;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(equipWeapon / 8).");

			Property pAvatar_exp = new Property();
			pAvatar_exp.name = "exp";
			pAvatar_exp.properUtype = 23;
			pAvatar_exp.properFlags = 16;
			pAvatar_exp.aliasID = 15;
			UInt64 Avatar_exp_defval;
			UInt64.TryParse("", out Avatar_exp_defval);
			pAvatar_exp.defaultVal = Avatar_exp_defval;
			pAvatarModule.propertys["exp"] = pAvatar_exp; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_exp.aliasID] = pAvatar_exp;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(exp / 23).");

			Property pAvatar_forbids = new Property();
			pAvatar_forbids.name = "forbids";
			pAvatar_forbids.properUtype = 47005;
			pAvatar_forbids.properFlags = 4;
			pAvatar_forbids.aliasID = 16;
			Int32 Avatar_forbids_defval;
			Int32.TryParse("0", out Avatar_forbids_defval);
			pAvatar_forbids.defaultVal = Avatar_forbids_defval;
			pAvatarModule.propertys["forbids"] = pAvatar_forbids; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_forbids.aliasID] = pAvatar_forbids;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(forbids / 47005).");

			Property pAvatar_itemList = new Property();
			pAvatar_itemList.name = "itemList";
			pAvatar_itemList.properUtype = 6;
			pAvatar_itemList.properFlags = 32;
			pAvatar_itemList.aliasID = 17;
			pAvatar_itemList.defaultVal = EntityDef.id2datatypes[28].parseDefaultValStr("");
			pAvatarModule.propertys["itemList"] = pAvatar_itemList; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_itemList.aliasID] = pAvatar_itemList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(itemList / 6).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 5;
			pAvatar_level.properFlags = 8;
			pAvatar_level.aliasID = 18;
			UInt16 Avatar_level_defval;
			UInt16.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 5).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 41006;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 19;
			UInt32 Avatar_modelID_defval;
			UInt32.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 41006).");

			Property pAvatar_modelScale = new Property();
			pAvatar_modelScale.name = "modelScale";
			pAvatar_modelScale.properUtype = 41007;
			pAvatar_modelScale.properFlags = 4;
			pAvatar_modelScale.aliasID = 20;
			Byte Avatar_modelScale_defval;
			Byte.TryParse("30", out Avatar_modelScale_defval);
			pAvatar_modelScale.defaultVal = Avatar_modelScale_defval;
			pAvatarModule.propertys["modelScale"] = pAvatar_modelScale; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelScale.aliasID] = pAvatar_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelScale / 41007).");

			Property pAvatar_money = new Property();
			pAvatar_money.name = "money";
			pAvatar_money.properUtype = 22;
			pAvatar_money.properFlags = 16;
			pAvatar_money.aliasID = 21;
			UInt64 Avatar_money_defval;
			UInt64.TryParse("", out Avatar_money_defval);
			pAvatar_money.defaultVal = Avatar_money_defval;
			pAvatarModule.propertys["money"] = pAvatar_money; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_money.aliasID] = pAvatar_money;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(money / 22).");

			Property pAvatar_moveSpeed = new Property();
			pAvatar_moveSpeed.name = "moveSpeed";
			pAvatar_moveSpeed.properUtype = 12;
			pAvatar_moveSpeed.properFlags = 4;
			pAvatar_moveSpeed.aliasID = 22;
			Byte Avatar_moveSpeed_defval;
			Byte.TryParse("50", out Avatar_moveSpeed_defval);
			pAvatar_moveSpeed.defaultVal = Avatar_moveSpeed_defval;
			pAvatarModule.propertys["moveSpeed"] = pAvatar_moveSpeed; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_moveSpeed.aliasID] = pAvatar_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(moveSpeed / 12).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 41003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 23;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 41003).");

			Property pAvatar_rating = new Property();
			pAvatar_rating.name = "rating";
			pAvatar_rating.properUtype = 20;
			pAvatar_rating.properFlags = 16;
			pAvatar_rating.aliasID = 24;
			Int32 Avatar_rating_defval;
			Int32.TryParse("99", out Avatar_rating_defval);
			pAvatar_rating.defaultVal = Avatar_rating_defval;
			pAvatarModule.propertys["rating"] = pAvatar_rating; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_rating.aliasID] = pAvatar_rating;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(rating / 20).");

			Property pAvatar_roleTypeCell = new Property();
			pAvatar_roleTypeCell.name = "roleTypeCell";
			pAvatar_roleTypeCell.properUtype = 4;
			pAvatar_roleTypeCell.properFlags = 4;
			pAvatar_roleTypeCell.aliasID = 25;
			Byte Avatar_roleTypeCell_defval;
			Byte.TryParse("", out Avatar_roleTypeCell_defval);
			pAvatar_roleTypeCell.defaultVal = Avatar_roleTypeCell_defval;
			pAvatarModule.propertys["roleTypeCell"] = pAvatar_roleTypeCell; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_roleTypeCell.aliasID] = pAvatar_roleTypeCell;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(roleTypeCell / 4).");

			Property pAvatar_spaceUType = new Property();
			pAvatar_spaceUType.name = "spaceUType";
			pAvatar_spaceUType.properUtype = 41001;
			pAvatar_spaceUType.properFlags = 8;
			pAvatar_spaceUType.aliasID = 26;
			UInt32 Avatar_spaceUType_defval;
			UInt32.TryParse("", out Avatar_spaceUType_defval);
			pAvatar_spaceUType.defaultVal = Avatar_spaceUType_defval;
			pAvatarModule.propertys["spaceUType"] = pAvatar_spaceUType; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceUType.aliasID] = pAvatar_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceUType / 41001).");

			Property pAvatar_stamina = new Property();
			pAvatar_stamina.name = "stamina";
			pAvatar_stamina.properUtype = 26;
			pAvatar_stamina.properFlags = 16;
			pAvatar_stamina.aliasID = 27;
			Int32 Avatar_stamina_defval;
			Int32.TryParse("", out Avatar_stamina_defval);
			pAvatar_stamina.defaultVal = Avatar_stamina_defval;
			pAvatarModule.propertys["stamina"] = pAvatar_stamina; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_stamina.aliasID] = pAvatar_stamina;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(stamina / 26).");

			Property pAvatar_state = new Property();
			pAvatar_state.name = "state";
			pAvatar_state.properUtype = 47006;
			pAvatar_state.properFlags = 4;
			pAvatar_state.aliasID = 28;
			SByte Avatar_state_defval;
			SByte.TryParse("0", out Avatar_state_defval);
			pAvatar_state.defaultVal = Avatar_state_defval;
			pAvatarModule.propertys["state"] = pAvatar_state; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_state.aliasID] = pAvatar_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(state / 47006).");

			Property pAvatar_strength = new Property();
			pAvatar_strength.name = "strength";
			pAvatar_strength.properUtype = 24;
			pAvatar_strength.properFlags = 16;
			pAvatar_strength.aliasID = 29;
			Int32 Avatar_strength_defval;
			Int32.TryParse("", out Avatar_strength_defval);
			pAvatar_strength.defaultVal = Avatar_strength_defval;
			pAvatarModule.propertys["strength"] = pAvatar_strength; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_strength.aliasID] = pAvatar_strength;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(strength / 24).");

			Property pAvatar_subState = new Property();
			pAvatar_subState.name = "subState";
			pAvatar_subState.properUtype = 47007;
			pAvatar_subState.properFlags = 4;
			pAvatar_subState.aliasID = 30;
			Byte Avatar_subState_defval;
			Byte.TryParse("", out Avatar_subState_defval);
			pAvatar_subState.defaultVal = Avatar_subState_defval;
			pAvatarModule.propertys["subState"] = pAvatar_subState; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_subState.aliasID] = pAvatar_subState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(subState / 47007).");

			Property pAvatar_uid = new Property();
			pAvatar_uid.name = "uid";
			pAvatar_uid.properUtype = 41004;
			pAvatar_uid.properFlags = 4;
			pAvatar_uid.aliasID = 31;
			UInt32 Avatar_uid_defval;
			UInt32.TryParse("0", out Avatar_uid_defval);
			pAvatar_uid.defaultVal = Avatar_uid_defval;
			pAvatarModule.propertys["uid"] = pAvatar_uid; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_uid.aliasID] = pAvatar_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(uid / 41004).");

			Property pAvatar_utype = new Property();
			pAvatar_utype.name = "utype";
			pAvatar_utype.properUtype = 41005;
			pAvatar_utype.properFlags = 4;
			pAvatar_utype.aliasID = 32;
			UInt32 Avatar_utype_defval;
			UInt32.TryParse("0", out Avatar_utype_defval);
			pAvatar_utype.defaultVal = Avatar_utype_defval;
			pAvatarModule.propertys["utype"] = pAvatar_utype; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_utype.aliasID] = pAvatar_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(utype / 41005).");

			List<DATATYPE_BASE> pAvatar_ReceiveChatMessage_args = new List<DATATYPE_BASE>();
			pAvatar_ReceiveChatMessage_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_ReceiveChatMessage = new Method();
			pAvatar_ReceiveChatMessage.name = "ReceiveChatMessage";
			pAvatar_ReceiveChatMessage.methodUtype = 21;
			pAvatar_ReceiveChatMessage.aliasID = 1;
			pAvatar_ReceiveChatMessage.args = pAvatar_ReceiveChatMessage_args;

			pAvatarModule.methods["ReceiveChatMessage"] = pAvatar_ReceiveChatMessage; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_ReceiveChatMessage.aliasID] = pAvatar_ReceiveChatMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(ReceiveChatMessage / 21).");

			List<DATATYPE_BASE> pAvatar_dialog_close_args = new List<DATATYPE_BASE>();

			Method pAvatar_dialog_close = new Method();
			pAvatar_dialog_close.name = "dialog_close";
			pAvatar_dialog_close.methodUtype = 10104;
			pAvatar_dialog_close.aliasID = 2;
			pAvatar_dialog_close.args = pAvatar_dialog_close_args;

			pAvatarModule.methods["dialog_close"] = pAvatar_dialog_close; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dialog_close.aliasID] = pAvatar_dialog_close;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog_close / 10104).");

			List<DATATYPE_BASE> pAvatar_dialog_setContent_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[31]);
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[32]);
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[12]);
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[12]);
			pAvatar_dialog_setContent_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_dialog_setContent = new Method();
			pAvatar_dialog_setContent.name = "dialog_setContent";
			pAvatar_dialog_setContent.methodUtype = 10101;
			pAvatar_dialog_setContent.aliasID = 3;
			pAvatar_dialog_setContent.args = pAvatar_dialog_setContent_args;

			pAvatarModule.methods["dialog_setContent"] = pAvatar_dialog_setContent; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dialog_setContent.aliasID] = pAvatar_dialog_setContent;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog_setContent / 10101).");

			List<DATATYPE_BASE> pAvatar_dropItem_re_args = new List<DATATYPE_BASE>();
			pAvatar_dropItem_re_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_dropItem_re_args.Add(EntityDef.id2datatypes[5]);

			Method pAvatar_dropItem_re = new Method();
			pAvatar_dropItem_re.name = "dropItem_re";
			pAvatar_dropItem_re.methodUtype = 24;
			pAvatar_dropItem_re.aliasID = 4;
			pAvatar_dropItem_re.args = pAvatar_dropItem_re_args;

			pAvatarModule.methods["dropItem_re"] = pAvatar_dropItem_re; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dropItem_re.aliasID] = pAvatar_dropItem_re;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dropItem_re / 24).");

			List<DATATYPE_BASE> pAvatar_equipItemRequest_re_args = new List<DATATYPE_BASE>();
			pAvatar_equipItemRequest_re_args.Add(EntityDef.id2datatypes[27]);
			pAvatar_equipItemRequest_re_args.Add(EntityDef.id2datatypes[27]);

			Method pAvatar_equipItemRequest_re = new Method();
			pAvatar_equipItemRequest_re.name = "equipItemRequest_re";
			pAvatar_equipItemRequest_re.methodUtype = 25;
			pAvatar_equipItemRequest_re.aliasID = 5;
			pAvatar_equipItemRequest_re.args = pAvatar_equipItemRequest_re_args;

			pAvatarModule.methods["equipItemRequest_re"] = pAvatar_equipItemRequest_re; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_equipItemRequest_re.aliasID] = pAvatar_equipItemRequest_re;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(equipItemRequest_re / 25).");

			List<DATATYPE_BASE> pAvatar_errorInfo_args = new List<DATATYPE_BASE>();
			pAvatar_errorInfo_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_errorInfo = new Method();
			pAvatar_errorInfo.name = "errorInfo";
			pAvatar_errorInfo.methodUtype = 26;
			pAvatar_errorInfo.aliasID = 6;
			pAvatar_errorInfo.args = pAvatar_errorInfo_args;

			pAvatarModule.methods["errorInfo"] = pAvatar_errorInfo; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_errorInfo.aliasID] = pAvatar_errorInfo;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(errorInfo / 26).");

			List<DATATYPE_BASE> pAvatar_onAddSkill_args = new List<DATATYPE_BASE>();
			pAvatar_onAddSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onAddSkill = new Method();
			pAvatar_onAddSkill.name = "onAddSkill";
			pAvatar_onAddSkill.methodUtype = 31;
			pAvatar_onAddSkill.aliasID = 7;
			pAvatar_onAddSkill.args = pAvatar_onAddSkill_args;

			pAvatarModule.methods["onAddSkill"] = pAvatar_onAddSkill; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onAddSkill.aliasID] = pAvatar_onAddSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onAddSkill / 31).");

			List<DATATYPE_BASE> pAvatar_onRemoveSkill_args = new List<DATATYPE_BASE>();
			pAvatar_onRemoveSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onRemoveSkill = new Method();
			pAvatar_onRemoveSkill.name = "onRemoveSkill";
			pAvatar_onRemoveSkill.methodUtype = 32;
			pAvatar_onRemoveSkill.aliasID = 8;
			pAvatar_onRemoveSkill.args = pAvatar_onRemoveSkill_args;

			pAvatarModule.methods["onRemoveSkill"] = pAvatar_onRemoveSkill; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onRemoveSkill.aliasID] = pAvatar_onRemoveSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onRemoveSkill / 32).");

			List<DATATYPE_BASE> pAvatar_onReqItemList_args = new List<DATATYPE_BASE>();
			pAvatar_onReqItemList_args.Add(EntityDef.id2datatypes[28]);
			pAvatar_onReqItemList_args.Add(EntityDef.id2datatypes[28]);

			Method pAvatar_onReqItemList = new Method();
			pAvatar_onReqItemList.name = "onReqItemList";
			pAvatar_onReqItemList.methodUtype = 22;
			pAvatar_onReqItemList.aliasID = 9;
			pAvatar_onReqItemList.args = pAvatar_onReqItemList_args;

			pAvatarModule.methods["onReqItemList"] = pAvatar_onReqItemList; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onReqItemList.aliasID] = pAvatar_onReqItemList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onReqItemList / 22).");

			List<DATATYPE_BASE> pAvatar_pickUp_re_args = new List<DATATYPE_BASE>();
			pAvatar_pickUp_re_args.Add(EntityDef.id2datatypes[27]);

			Method pAvatar_pickUp_re = new Method();
			pAvatar_pickUp_re.name = "pickUp_re";
			pAvatar_pickUp_re.methodUtype = 23;
			pAvatar_pickUp_re.aliasID = 10;
			pAvatar_pickUp_re.args = pAvatar_pickUp_re_args;

			pAvatarModule.methods["pickUp_re"] = pAvatar_pickUp_re; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_pickUp_re.aliasID] = pAvatar_pickUp_re;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(pickUp_re / 23).");

			List<DATATYPE_BASE> pAvatar_recvDamage_args = new List<DATATYPE_BASE>();
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_recvDamage = new Method();
			pAvatar_recvDamage.name = "recvDamage";
			pAvatar_recvDamage.methodUtype = 35;
			pAvatar_recvDamage.aliasID = 11;
			pAvatar_recvDamage.args = pAvatar_recvDamage_args;

			pAvatarModule.methods["recvDamage"] = pAvatar_recvDamage; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_recvDamage.aliasID] = pAvatar_recvDamage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(recvDamage / 35).");

			List<DATATYPE_BASE> pAvatar_dropRequest_args = new List<DATATYPE_BASE>();
			pAvatar_dropRequest_args.Add(EntityDef.id2datatypes[5]);

			Method pAvatar_dropRequest = new Method();
			pAvatar_dropRequest.name = "dropRequest";
			pAvatar_dropRequest.methodUtype = 16;
			pAvatar_dropRequest.aliasID = -1;
			pAvatar_dropRequest.args = pAvatar_dropRequest_args;

			pAvatarModule.methods["dropRequest"] = pAvatar_dropRequest; 
			pAvatarModule.base_methods["dropRequest"] = pAvatar_dropRequest;

			pAvatarModule.idbase_methods[pAvatar_dropRequest.methodUtype] = pAvatar_dropRequest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dropRequest / 16).");

			List<DATATYPE_BASE> pAvatar_equipItemRequest_args = new List<DATATYPE_BASE>();
			pAvatar_equipItemRequest_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_equipItemRequest_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_equipItemRequest = new Method();
			pAvatar_equipItemRequest.name = "equipItemRequest";
			pAvatar_equipItemRequest.methodUtype = 18;
			pAvatar_equipItemRequest.aliasID = -1;
			pAvatar_equipItemRequest.args = pAvatar_equipItemRequest_args;

			pAvatarModule.methods["equipItemRequest"] = pAvatar_equipItemRequest; 
			pAvatarModule.base_methods["equipItemRequest"] = pAvatar_equipItemRequest;

			pAvatarModule.idbase_methods[pAvatar_equipItemRequest.methodUtype] = pAvatar_equipItemRequest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(equipItemRequest / 18).");

			List<DATATYPE_BASE> pAvatar_reqItemList_args = new List<DATATYPE_BASE>();

			Method pAvatar_reqItemList = new Method();
			pAvatar_reqItemList.name = "reqItemList";
			pAvatar_reqItemList.methodUtype = 14;
			pAvatar_reqItemList.aliasID = -1;
			pAvatar_reqItemList.args = pAvatar_reqItemList_args;

			pAvatarModule.methods["reqItemList"] = pAvatar_reqItemList; 
			pAvatarModule.base_methods["reqItemList"] = pAvatar_reqItemList;

			pAvatarModule.idbase_methods[pAvatar_reqItemList.methodUtype] = pAvatar_reqItemList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqItemList / 14).");

			List<DATATYPE_BASE> pAvatar_sendChatMessage_args = new List<DATATYPE_BASE>();
			pAvatar_sendChatMessage_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_sendChatMessage = new Method();
			pAvatar_sendChatMessage.name = "sendChatMessage";
			pAvatar_sendChatMessage.methodUtype = 13;
			pAvatar_sendChatMessage.aliasID = -1;
			pAvatar_sendChatMessage.args = pAvatar_sendChatMessage_args;

			pAvatarModule.methods["sendChatMessage"] = pAvatar_sendChatMessage; 
			pAvatarModule.base_methods["sendChatMessage"] = pAvatar_sendChatMessage;

			pAvatarModule.idbase_methods[pAvatar_sendChatMessage.methodUtype] = pAvatar_sendChatMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(sendChatMessage / 13).");

			List<DATATYPE_BASE> pAvatar_swapItemRequest_args = new List<DATATYPE_BASE>();
			pAvatar_swapItemRequest_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_swapItemRequest_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_swapItemRequest = new Method();
			pAvatar_swapItemRequest.name = "swapItemRequest";
			pAvatar_swapItemRequest.methodUtype = 17;
			pAvatar_swapItemRequest.aliasID = -1;
			pAvatar_swapItemRequest.args = pAvatar_swapItemRequest_args;

			pAvatarModule.methods["swapItemRequest"] = pAvatar_swapItemRequest; 
			pAvatarModule.base_methods["swapItemRequest"] = pAvatar_swapItemRequest;

			pAvatarModule.idbase_methods[pAvatar_swapItemRequest.methodUtype] = pAvatar_swapItemRequest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(swapItemRequest / 17).");

			List<DATATYPE_BASE> pAvatar_useItemRequest_args = new List<DATATYPE_BASE>();
			pAvatar_useItemRequest_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_useItemRequest = new Method();
			pAvatar_useItemRequest.name = "useItemRequest";
			pAvatar_useItemRequest.methodUtype = 20;
			pAvatar_useItemRequest.aliasID = -1;
			pAvatar_useItemRequest.args = pAvatar_useItemRequest_args;

			pAvatarModule.methods["useItemRequest"] = pAvatar_useItemRequest; 
			pAvatarModule.base_methods["useItemRequest"] = pAvatar_useItemRequest;

			pAvatarModule.idbase_methods[pAvatar_useItemRequest.methodUtype] = pAvatar_useItemRequest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(useItemRequest / 20).");

			List<DATATYPE_BASE> pAvatar_dialog_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_dialog = new Method();
			pAvatar_dialog.name = "dialog";
			pAvatar_dialog.methodUtype = 11003;
			pAvatar_dialog.aliasID = -1;
			pAvatar_dialog.args = pAvatar_dialog_args;

			pAvatarModule.methods["dialog"] = pAvatar_dialog; 
			pAvatarModule.cell_methods["dialog"] = pAvatar_dialog;

			pAvatarModule.idcell_methods[pAvatar_dialog.methodUtype] = pAvatar_dialog;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog / 11003).");

			List<DATATYPE_BASE> pAvatar_relive_args = new List<DATATYPE_BASE>();
			pAvatar_relive_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_relive = new Method();
			pAvatar_relive.name = "relive";
			pAvatar_relive.methodUtype = 8;
			pAvatar_relive.aliasID = -1;
			pAvatar_relive.args = pAvatar_relive_args;

			pAvatarModule.methods["relive"] = pAvatar_relive; 
			pAvatarModule.cell_methods["relive"] = pAvatar_relive;

			pAvatarModule.idcell_methods[pAvatar_relive.methodUtype] = pAvatar_relive;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(relive / 8).");

			List<DATATYPE_BASE> pAvatar_requestPull_args = new List<DATATYPE_BASE>();

			Method pAvatar_requestPull = new Method();
			pAvatar_requestPull.name = "requestPull";
			pAvatar_requestPull.methodUtype = 30;
			pAvatar_requestPull.aliasID = -1;
			pAvatar_requestPull.args = pAvatar_requestPull_args;

			pAvatarModule.methods["requestPull"] = pAvatar_requestPull; 
			pAvatarModule.cell_methods["requestPull"] = pAvatar_requestPull;

			pAvatarModule.idcell_methods[pAvatar_requestPull.methodUtype] = pAvatar_requestPull;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(requestPull / 30).");

			List<DATATYPE_BASE> pAvatar_useTargetSkill_args = new List<DATATYPE_BASE>();
			pAvatar_useTargetSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_useTargetSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_useTargetSkill = new Method();
			pAvatar_useTargetSkill.name = "useTargetSkill";
			pAvatar_useTargetSkill.methodUtype = 11001;
			pAvatar_useTargetSkill.aliasID = -1;
			pAvatar_useTargetSkill.args = pAvatar_useTargetSkill_args;

			pAvatarModule.methods["useTargetSkill"] = pAvatar_useTargetSkill; 
			pAvatarModule.cell_methods["useTargetSkill"] = pAvatar_useTargetSkill;

			pAvatarModule.idcell_methods[pAvatar_useTargetSkill.methodUtype] = pAvatar_useTargetSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(useTargetSkill / 11001).");

			ScriptModule pMonsterModule = new ScriptModule("Monster");
			EntityDef.moduledefs["Monster"] = pMonsterModule;
			EntityDef.idmoduledefs[3] = pMonsterModule;

			Property pMonster_position = new Property();
			pMonster_position.name = "position";
			pMonster_position.properUtype = 40000;
			pMonster_position.properFlags = 4;
			pMonster_position.aliasID = 1;
			Vector3 Monster_position_defval = new Vector3();
			pMonster_position.defaultVal = Monster_position_defval;
			pMonsterModule.propertys["position"] = pMonster_position; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_position.aliasID] = pMonster_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(position / 40000).");

			Property pMonster_direction = new Property();
			pMonster_direction.name = "direction";
			pMonster_direction.properUtype = 40001;
			pMonster_direction.properFlags = 4;
			pMonster_direction.aliasID = 2;
			Vector3 Monster_direction_defval = new Vector3();
			pMonster_direction.defaultVal = Monster_direction_defval;
			pMonsterModule.propertys["direction"] = pMonster_direction; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_direction.aliasID] = pMonster_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(direction / 40001).");

			Property pMonster_spaceID = new Property();
			pMonster_spaceID.name = "spaceID";
			pMonster_spaceID.properUtype = 40002;
			pMonster_spaceID.properFlags = 16;
			pMonster_spaceID.aliasID = 3;
			UInt32 Monster_spaceID_defval;
			UInt32.TryParse("", out Monster_spaceID_defval);
			pMonster_spaceID.defaultVal = Monster_spaceID_defval;
			pMonsterModule.propertys["spaceID"] = pMonster_spaceID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_spaceID.aliasID] = pMonster_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(spaceID / 40002).");

			Property pMonster_HP = new Property();
			pMonster_HP.name = "HP";
			pMonster_HP.properUtype = 47001;
			pMonster_HP.properFlags = 4;
			pMonster_HP.aliasID = 4;
			Int32 Monster_HP_defval;
			Int32.TryParse("0", out Monster_HP_defval);
			pMonster_HP.defaultVal = Monster_HP_defval;
			pMonsterModule.propertys["HP"] = pMonster_HP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP.aliasID] = pMonster_HP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP / 47001).");

			Property pMonster_HP_Max = new Property();
			pMonster_HP_Max.name = "HP_Max";
			pMonster_HP_Max.properUtype = 47002;
			pMonster_HP_Max.properFlags = 4;
			pMonster_HP_Max.aliasID = 5;
			Int32 Monster_HP_Max_defval;
			Int32.TryParse("0", out Monster_HP_Max_defval);
			pMonster_HP_Max.defaultVal = Monster_HP_Max_defval;
			pMonsterModule.propertys["HP_Max"] = pMonster_HP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP_Max.aliasID] = pMonster_HP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP_Max / 47002).");

			Property pMonster_MP = new Property();
			pMonster_MP.name = "MP";
			pMonster_MP.properUtype = 47003;
			pMonster_MP.properFlags = 4;
			pMonster_MP.aliasID = 6;
			Int32 Monster_MP_defval;
			Int32.TryParse("0", out Monster_MP_defval);
			pMonster_MP.defaultVal = Monster_MP_defval;
			pMonsterModule.propertys["MP"] = pMonster_MP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP.aliasID] = pMonster_MP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP / 47003).");

			Property pMonster_MP_Max = new Property();
			pMonster_MP_Max.name = "MP_Max";
			pMonster_MP_Max.properUtype = 47004;
			pMonster_MP_Max.properFlags = 4;
			pMonster_MP_Max.aliasID = 7;
			Int32 Monster_MP_Max_defval;
			Int32.TryParse("0", out Monster_MP_Max_defval);
			pMonster_MP_Max.defaultVal = Monster_MP_Max_defval;
			pMonsterModule.propertys["MP_Max"] = pMonster_MP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP_Max.aliasID] = pMonster_MP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP_Max / 47004).");

			Property pMonster_attack_Max = new Property();
			pMonster_attack_Max.name = "attack_Max";
			pMonster_attack_Max.properUtype = 37;
			pMonster_attack_Max.properFlags = 16;
			pMonster_attack_Max.aliasID = 8;
			Int32 Monster_attack_Max_defval;
			Int32.TryParse("10", out Monster_attack_Max_defval);
			pMonster_attack_Max.defaultVal = Monster_attack_Max_defval;
			pMonsterModule.propertys["attack_Max"] = pMonster_attack_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_attack_Max.aliasID] = pMonster_attack_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(attack_Max / 37).");

			Property pMonster_attack_Min = new Property();
			pMonster_attack_Min.name = "attack_Min";
			pMonster_attack_Min.properUtype = 38;
			pMonster_attack_Min.properFlags = 16;
			pMonster_attack_Min.aliasID = 9;
			Int32 Monster_attack_Min_defval;
			Int32.TryParse("0", out Monster_attack_Min_defval);
			pMonster_attack_Min.defaultVal = Monster_attack_Min_defval;
			pMonsterModule.propertys["attack_Min"] = pMonster_attack_Min; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_attack_Min.aliasID] = pMonster_attack_Min;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(attack_Min / 38).");

			Property pMonster_defence = new Property();
			pMonster_defence.name = "defence";
			pMonster_defence.properUtype = 39;
			pMonster_defence.properFlags = 16;
			pMonster_defence.aliasID = 10;
			Int32 Monster_defence_defval;
			Int32.TryParse("0", out Monster_defence_defval);
			pMonster_defence.defaultVal = Monster_defence_defval;
			pMonsterModule.propertys["defence"] = pMonster_defence; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_defence.aliasID] = pMonster_defence;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(defence / 39).");

			Property pMonster_dialogID = new Property();
			pMonster_dialogID.name = "dialogID";
			pMonster_dialogID.properUtype = 32;
			pMonster_dialogID.properFlags = 4;
			pMonster_dialogID.aliasID = 11;
			UInt32 Monster_dialogID_defval;
			UInt32.TryParse("0", out Monster_dialogID_defval);
			pMonster_dialogID.defaultVal = Monster_dialogID_defval;
			pMonsterModule.propertys["dialogID"] = pMonster_dialogID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_dialogID.aliasID] = pMonster_dialogID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(dialogID / 32).");

			Property pMonster_dodge = new Property();
			pMonster_dodge.name = "dodge";
			pMonster_dodge.properUtype = 41;
			pMonster_dodge.properFlags = 16;
			pMonster_dodge.aliasID = 12;
			Int32 Monster_dodge_defval;
			Int32.TryParse("0", out Monster_dodge_defval);
			pMonster_dodge.defaultVal = Monster_dodge_defval;
			pMonsterModule.propertys["dodge"] = pMonster_dodge; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_dodge.aliasID] = pMonster_dodge;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(dodge / 41).");

			Property pMonster_entityNO = new Property();
			pMonster_entityNO.name = "entityNO";
			pMonster_entityNO.properUtype = 51007;
			pMonster_entityNO.properFlags = 4;
			pMonster_entityNO.aliasID = 13;
			UInt32 Monster_entityNO_defval;
			UInt32.TryParse("0", out Monster_entityNO_defval);
			pMonster_entityNO.defaultVal = Monster_entityNO_defval;
			pMonsterModule.propertys["entityNO"] = pMonster_entityNO; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_entityNO.aliasID] = pMonster_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(entityNO / 51007).");

			Property pMonster_forbids = new Property();
			pMonster_forbids.name = "forbids";
			pMonster_forbids.properUtype = 47005;
			pMonster_forbids.properFlags = 4;
			pMonster_forbids.aliasID = 14;
			Int32 Monster_forbids_defval;
			Int32.TryParse("0", out Monster_forbids_defval);
			pMonster_forbids.defaultVal = Monster_forbids_defval;
			pMonsterModule.propertys["forbids"] = pMonster_forbids; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_forbids.aliasID] = pMonster_forbids;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(forbids / 47005).");

			Property pMonster_modelID = new Property();
			pMonster_modelID.name = "modelID";
			pMonster_modelID.properUtype = 41006;
			pMonster_modelID.properFlags = 4;
			pMonster_modelID.aliasID = 15;
			UInt32 Monster_modelID_defval;
			UInt32.TryParse("0", out Monster_modelID_defval);
			pMonster_modelID.defaultVal = Monster_modelID_defval;
			pMonsterModule.propertys["modelID"] = pMonster_modelID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_modelID.aliasID] = pMonster_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(modelID / 41006).");

			Property pMonster_modelScale = new Property();
			pMonster_modelScale.name = "modelScale";
			pMonster_modelScale.properUtype = 41007;
			pMonster_modelScale.properFlags = 4;
			pMonster_modelScale.aliasID = 16;
			Byte Monster_modelScale_defval;
			Byte.TryParse("30", out Monster_modelScale_defval);
			pMonster_modelScale.defaultVal = Monster_modelScale_defval;
			pMonsterModule.propertys["modelScale"] = pMonster_modelScale; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_modelScale.aliasID] = pMonster_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(modelScale / 41007).");

			Property pMonster_moveSpeed = new Property();
			pMonster_moveSpeed.name = "moveSpeed";
			pMonster_moveSpeed.properUtype = 33;
			pMonster_moveSpeed.properFlags = 4;
			pMonster_moveSpeed.aliasID = 17;
			Byte Monster_moveSpeed_defval;
			Byte.TryParse("50", out Monster_moveSpeed_defval);
			pMonster_moveSpeed.defaultVal = Monster_moveSpeed_defval;
			pMonsterModule.propertys["moveSpeed"] = pMonster_moveSpeed; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_moveSpeed.aliasID] = pMonster_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(moveSpeed / 33).");

			Property pMonster_name = new Property();
			pMonster_name.name = "name";
			pMonster_name.properUtype = 41003;
			pMonster_name.properFlags = 4;
			pMonster_name.aliasID = 18;
			string Monster_name_defval = "";
			pMonster_name.defaultVal = Monster_name_defval;
			pMonsterModule.propertys["name"] = pMonster_name; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_name.aliasID] = pMonster_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(name / 41003).");

			Property pMonster_rating = new Property();
			pMonster_rating.name = "rating";
			pMonster_rating.properUtype = 40;
			pMonster_rating.properFlags = 16;
			pMonster_rating.aliasID = 19;
			Int32 Monster_rating_defval;
			Int32.TryParse("99", out Monster_rating_defval);
			pMonster_rating.defaultVal = Monster_rating_defval;
			pMonsterModule.propertys["rating"] = pMonster_rating; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_rating.aliasID] = pMonster_rating;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(rating / 40).");

			Property pMonster_state = new Property();
			pMonster_state.name = "state";
			pMonster_state.properUtype = 47006;
			pMonster_state.properFlags = 4;
			pMonster_state.aliasID = 20;
			SByte Monster_state_defval;
			SByte.TryParse("0", out Monster_state_defval);
			pMonster_state.defaultVal = Monster_state_defval;
			pMonsterModule.propertys["state"] = pMonster_state; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_state.aliasID] = pMonster_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(state / 47006).");

			Property pMonster_subState = new Property();
			pMonster_subState.name = "subState";
			pMonster_subState.properUtype = 47007;
			pMonster_subState.properFlags = 4;
			pMonster_subState.aliasID = 21;
			Byte Monster_subState_defval;
			Byte.TryParse("", out Monster_subState_defval);
			pMonster_subState.defaultVal = Monster_subState_defval;
			pMonsterModule.propertys["subState"] = pMonster_subState; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_subState.aliasID] = pMonster_subState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(subState / 47007).");

			Property pMonster_uid = new Property();
			pMonster_uid.name = "uid";
			pMonster_uid.properUtype = 41004;
			pMonster_uid.properFlags = 4;
			pMonster_uid.aliasID = 22;
			UInt32 Monster_uid_defval;
			UInt32.TryParse("0", out Monster_uid_defval);
			pMonster_uid.defaultVal = Monster_uid_defval;
			pMonsterModule.propertys["uid"] = pMonster_uid; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_uid.aliasID] = pMonster_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(uid / 41004).");

			Property pMonster_utype = new Property();
			pMonster_utype.name = "utype";
			pMonster_utype.properUtype = 41005;
			pMonster_utype.properFlags = 4;
			pMonster_utype.aliasID = 23;
			UInt32 Monster_utype_defval;
			UInt32.TryParse("0", out Monster_utype_defval);
			pMonster_utype.defaultVal = Monster_utype_defval;
			pMonsterModule.propertys["utype"] = pMonster_utype; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_utype.aliasID] = pMonster_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(utype / 41005).");

			List<DATATYPE_BASE> pMonster_recvDamage_args = new List<DATATYPE_BASE>();
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);

			Method pMonster_recvDamage = new Method();
			pMonster_recvDamage.name = "recvDamage";
			pMonster_recvDamage.methodUtype = 52;
			pMonster_recvDamage.aliasID = 1;
			pMonster_recvDamage.args = pMonster_recvDamage_args;

			pMonsterModule.methods["recvDamage"] = pMonster_recvDamage; 
			pMonsterModule.useMethodDescrAlias = true;
			pMonsterModule.idmethods[(UInt16)pMonster_recvDamage.aliasID] = pMonster_recvDamage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), method(recvDamage / 52).");

			ScriptModule pNPCModule = new ScriptModule("NPC");
			EntityDef.moduledefs["NPC"] = pNPCModule;
			EntityDef.idmoduledefs[4] = pNPCModule;

			Property pNPC_position = new Property();
			pNPC_position.name = "position";
			pNPC_position.properUtype = 40000;
			pNPC_position.properFlags = 4;
			pNPC_position.aliasID = 1;
			Vector3 NPC_position_defval = new Vector3();
			pNPC_position.defaultVal = NPC_position_defval;
			pNPCModule.propertys["position"] = pNPC_position; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_position.aliasID] = pNPC_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(position / 40000).");

			Property pNPC_direction = new Property();
			pNPC_direction.name = "direction";
			pNPC_direction.properUtype = 40001;
			pNPC_direction.properFlags = 4;
			pNPC_direction.aliasID = 2;
			Vector3 NPC_direction_defval = new Vector3();
			pNPC_direction.defaultVal = NPC_direction_defval;
			pNPCModule.propertys["direction"] = pNPC_direction; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_direction.aliasID] = pNPC_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(direction / 40001).");

			Property pNPC_spaceID = new Property();
			pNPC_spaceID.name = "spaceID";
			pNPC_spaceID.properUtype = 40002;
			pNPC_spaceID.properFlags = 16;
			pNPC_spaceID.aliasID = 3;
			UInt32 NPC_spaceID_defval;
			UInt32.TryParse("", out NPC_spaceID_defval);
			pNPC_spaceID.defaultVal = NPC_spaceID_defval;
			pNPCModule.propertys["spaceID"] = pNPC_spaceID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_spaceID.aliasID] = pNPC_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(spaceID / 40002).");

			Property pNPC_dialogID = new Property();
			pNPC_dialogID.name = "dialogID";
			pNPC_dialogID.properUtype = 49;
			pNPC_dialogID.properFlags = 4;
			pNPC_dialogID.aliasID = 4;
			UInt32 NPC_dialogID_defval;
			UInt32.TryParse("0", out NPC_dialogID_defval);
			pNPC_dialogID.defaultVal = NPC_dialogID_defval;
			pNPCModule.propertys["dialogID"] = pNPC_dialogID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_dialogID.aliasID] = pNPC_dialogID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(dialogID / 49).");

			Property pNPC_entityNO = new Property();
			pNPC_entityNO.name = "entityNO";
			pNPC_entityNO.properUtype = 51007;
			pNPC_entityNO.properFlags = 4;
			pNPC_entityNO.aliasID = 5;
			UInt32 NPC_entityNO_defval;
			UInt32.TryParse("0", out NPC_entityNO_defval);
			pNPC_entityNO.defaultVal = NPC_entityNO_defval;
			pNPCModule.propertys["entityNO"] = pNPC_entityNO; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_entityNO.aliasID] = pNPC_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(entityNO / 51007).");

			Property pNPC_modelID = new Property();
			pNPC_modelID.name = "modelID";
			pNPC_modelID.properUtype = 41006;
			pNPC_modelID.properFlags = 4;
			pNPC_modelID.aliasID = 6;
			UInt32 NPC_modelID_defval;
			UInt32.TryParse("0", out NPC_modelID_defval);
			pNPC_modelID.defaultVal = NPC_modelID_defval;
			pNPCModule.propertys["modelID"] = pNPC_modelID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_modelID.aliasID] = pNPC_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(modelID / 41006).");

			Property pNPC_modelScale = new Property();
			pNPC_modelScale.name = "modelScale";
			pNPC_modelScale.properUtype = 41007;
			pNPC_modelScale.properFlags = 4;
			pNPC_modelScale.aliasID = 7;
			Byte NPC_modelScale_defval;
			Byte.TryParse("30", out NPC_modelScale_defval);
			pNPC_modelScale.defaultVal = NPC_modelScale_defval;
			pNPCModule.propertys["modelScale"] = pNPC_modelScale; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_modelScale.aliasID] = pNPC_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(modelScale / 41007).");

			Property pNPC_moveSpeed = new Property();
			pNPC_moveSpeed.name = "moveSpeed";
			pNPC_moveSpeed.properUtype = 50;
			pNPC_moveSpeed.properFlags = 4;
			pNPC_moveSpeed.aliasID = 8;
			Byte NPC_moveSpeed_defval;
			Byte.TryParse("50", out NPC_moveSpeed_defval);
			pNPC_moveSpeed.defaultVal = NPC_moveSpeed_defval;
			pNPCModule.propertys["moveSpeed"] = pNPC_moveSpeed; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_moveSpeed.aliasID] = pNPC_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(moveSpeed / 50).");

			Property pNPC_name = new Property();
			pNPC_name.name = "name";
			pNPC_name.properUtype = 41003;
			pNPC_name.properFlags = 4;
			pNPC_name.aliasID = 9;
			string NPC_name_defval = "";
			pNPC_name.defaultVal = NPC_name_defval;
			pNPCModule.propertys["name"] = pNPC_name; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_name.aliasID] = pNPC_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(name / 41003).");

			Property pNPC_uid = new Property();
			pNPC_uid.name = "uid";
			pNPC_uid.properUtype = 41004;
			pNPC_uid.properFlags = 4;
			pNPC_uid.aliasID = 10;
			UInt32 NPC_uid_defval;
			UInt32.TryParse("0", out NPC_uid_defval);
			pNPC_uid.defaultVal = NPC_uid_defval;
			pNPCModule.propertys["uid"] = pNPC_uid; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_uid.aliasID] = pNPC_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(uid / 41004).");

			Property pNPC_utype = new Property();
			pNPC_utype.name = "utype";
			pNPC_utype.properUtype = 41005;
			pNPC_utype.properFlags = 4;
			pNPC_utype.aliasID = 11;
			UInt32 NPC_utype_defval;
			UInt32.TryParse("0", out NPC_utype_defval);
			pNPC_utype.defaultVal = NPC_utype_defval;
			pNPCModule.propertys["utype"] = pNPC_utype; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_utype.aliasID] = pNPC_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(utype / 41005).");

			ScriptModule pGateModule = new ScriptModule("Gate");
			EntityDef.moduledefs["Gate"] = pGateModule;
			EntityDef.idmoduledefs[5] = pGateModule;

			Property pGate_position = new Property();
			pGate_position.name = "position";
			pGate_position.properUtype = 40000;
			pGate_position.properFlags = 4;
			pGate_position.aliasID = 1;
			Vector3 Gate_position_defval = new Vector3();
			pGate_position.defaultVal = Gate_position_defval;
			pGateModule.propertys["position"] = pGate_position; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_position.aliasID] = pGate_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(position / 40000).");

			Property pGate_direction = new Property();
			pGate_direction.name = "direction";
			pGate_direction.properUtype = 40001;
			pGate_direction.properFlags = 4;
			pGate_direction.aliasID = 2;
			Vector3 Gate_direction_defval = new Vector3();
			pGate_direction.defaultVal = Gate_direction_defval;
			pGateModule.propertys["direction"] = pGate_direction; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_direction.aliasID] = pGate_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(direction / 40001).");

			Property pGate_spaceID = new Property();
			pGate_spaceID.name = "spaceID";
			pGate_spaceID.properUtype = 40002;
			pGate_spaceID.properFlags = 16;
			pGate_spaceID.aliasID = 3;
			UInt32 Gate_spaceID_defval;
			UInt32.TryParse("", out Gate_spaceID_defval);
			pGate_spaceID.defaultVal = Gate_spaceID_defval;
			pGateModule.propertys["spaceID"] = pGate_spaceID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_spaceID.aliasID] = pGate_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(spaceID / 40002).");

			Property pGate_dialogID = new Property();
			pGate_dialogID.name = "dialogID";
			pGate_dialogID.properUtype = 57;
			pGate_dialogID.properFlags = 4;
			pGate_dialogID.aliasID = 4;
			UInt32 Gate_dialogID_defval;
			UInt32.TryParse("0", out Gate_dialogID_defval);
			pGate_dialogID.defaultVal = Gate_dialogID_defval;
			pGateModule.propertys["dialogID"] = pGate_dialogID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_dialogID.aliasID] = pGate_dialogID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(dialogID / 57).");

			Property pGate_entityNO = new Property();
			pGate_entityNO.name = "entityNO";
			pGate_entityNO.properUtype = 51007;
			pGate_entityNO.properFlags = 4;
			pGate_entityNO.aliasID = 5;
			UInt32 Gate_entityNO_defval;
			UInt32.TryParse("0", out Gate_entityNO_defval);
			pGate_entityNO.defaultVal = Gate_entityNO_defval;
			pGateModule.propertys["entityNO"] = pGate_entityNO; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_entityNO.aliasID] = pGate_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(entityNO / 51007).");

			Property pGate_modelID = new Property();
			pGate_modelID.name = "modelID";
			pGate_modelID.properUtype = 41006;
			pGate_modelID.properFlags = 4;
			pGate_modelID.aliasID = 6;
			UInt32 Gate_modelID_defval;
			UInt32.TryParse("0", out Gate_modelID_defval);
			pGate_modelID.defaultVal = Gate_modelID_defval;
			pGateModule.propertys["modelID"] = pGate_modelID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelID.aliasID] = pGate_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelID / 41006).");

			Property pGate_modelScale = new Property();
			pGate_modelScale.name = "modelScale";
			pGate_modelScale.properUtype = 41007;
			pGate_modelScale.properFlags = 4;
			pGate_modelScale.aliasID = 7;
			Byte Gate_modelScale_defval;
			Byte.TryParse("30", out Gate_modelScale_defval);
			pGate_modelScale.defaultVal = Gate_modelScale_defval;
			pGateModule.propertys["modelScale"] = pGate_modelScale; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelScale.aliasID] = pGate_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelScale / 41007).");

			Property pGate_name = new Property();
			pGate_name.name = "name";
			pGate_name.properUtype = 41003;
			pGate_name.properFlags = 4;
			pGate_name.aliasID = 8;
			string Gate_name_defval = "";
			pGate_name.defaultVal = Gate_name_defval;
			pGateModule.propertys["name"] = pGate_name; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_name.aliasID] = pGate_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(name / 41003).");

			Property pGate_uid = new Property();
			pGate_uid.name = "uid";
			pGate_uid.properUtype = 41004;
			pGate_uid.properFlags = 4;
			pGate_uid.aliasID = 9;
			UInt32 Gate_uid_defval;
			UInt32.TryParse("0", out Gate_uid_defval);
			pGate_uid.defaultVal = Gate_uid_defval;
			pGateModule.propertys["uid"] = pGate_uid; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_uid.aliasID] = pGate_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(uid / 41004).");

			Property pGate_utype = new Property();
			pGate_utype.name = "utype";
			pGate_utype.properUtype = 41005;
			pGate_utype.properFlags = 4;
			pGate_utype.aliasID = 10;
			UInt32 Gate_utype_defval;
			UInt32.TryParse("0", out Gate_utype_defval);
			pGate_utype.defaultVal = Gate_utype_defval;
			pGateModule.propertys["utype"] = pGate_utype; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_utype.aliasID] = pGate_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(utype / 41005).");

			ScriptModule pDroppedItemModule = new ScriptModule("DroppedItem");
			EntityDef.moduledefs["DroppedItem"] = pDroppedItemModule;
			EntityDef.idmoduledefs[6] = pDroppedItemModule;

			Property pDroppedItem_position = new Property();
			pDroppedItem_position.name = "position";
			pDroppedItem_position.properUtype = 40000;
			pDroppedItem_position.properFlags = 4;
			pDroppedItem_position.aliasID = 1;
			Vector3 DroppedItem_position_defval = new Vector3();
			pDroppedItem_position.defaultVal = DroppedItem_position_defval;
			pDroppedItemModule.propertys["position"] = pDroppedItem_position; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_position.aliasID] = pDroppedItem_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(position / 40000).");

			Property pDroppedItem_direction = new Property();
			pDroppedItem_direction.name = "direction";
			pDroppedItem_direction.properUtype = 40001;
			pDroppedItem_direction.properFlags = 4;
			pDroppedItem_direction.aliasID = 2;
			Vector3 DroppedItem_direction_defval = new Vector3();
			pDroppedItem_direction.defaultVal = DroppedItem_direction_defval;
			pDroppedItemModule.propertys["direction"] = pDroppedItem_direction; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_direction.aliasID] = pDroppedItem_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(direction / 40001).");

			Property pDroppedItem_spaceID = new Property();
			pDroppedItem_spaceID.name = "spaceID";
			pDroppedItem_spaceID.properUtype = 40002;
			pDroppedItem_spaceID.properFlags = 16;
			pDroppedItem_spaceID.aliasID = 3;
			UInt32 DroppedItem_spaceID_defval;
			UInt32.TryParse("", out DroppedItem_spaceID_defval);
			pDroppedItem_spaceID.defaultVal = DroppedItem_spaceID_defval;
			pDroppedItemModule.propertys["spaceID"] = pDroppedItem_spaceID; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_spaceID.aliasID] = pDroppedItem_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(spaceID / 40002).");

			Property pDroppedItem_dialogID = new Property();
			pDroppedItem_dialogID.name = "dialogID";
			pDroppedItem_dialogID.properUtype = 64;
			pDroppedItem_dialogID.properFlags = 4;
			pDroppedItem_dialogID.aliasID = 4;
			UInt32 DroppedItem_dialogID_defval;
			UInt32.TryParse("0", out DroppedItem_dialogID_defval);
			pDroppedItem_dialogID.defaultVal = DroppedItem_dialogID_defval;
			pDroppedItemModule.propertys["dialogID"] = pDroppedItem_dialogID; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_dialogID.aliasID] = pDroppedItem_dialogID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(dialogID / 64).");

			Property pDroppedItem_entityNO = new Property();
			pDroppedItem_entityNO.name = "entityNO";
			pDroppedItem_entityNO.properUtype = 51007;
			pDroppedItem_entityNO.properFlags = 4;
			pDroppedItem_entityNO.aliasID = 5;
			UInt32 DroppedItem_entityNO_defval;
			UInt32.TryParse("0", out DroppedItem_entityNO_defval);
			pDroppedItem_entityNO.defaultVal = DroppedItem_entityNO_defval;
			pDroppedItemModule.propertys["entityNO"] = pDroppedItem_entityNO; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_entityNO.aliasID] = pDroppedItem_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(entityNO / 51007).");

			Property pDroppedItem_itemCount = new Property();
			pDroppedItem_itemCount.name = "itemCount";
			pDroppedItem_itemCount.properUtype = 59;
			pDroppedItem_itemCount.properFlags = 4;
			pDroppedItem_itemCount.aliasID = 6;
			UInt32 DroppedItem_itemCount_defval;
			UInt32.TryParse("0", out DroppedItem_itemCount_defval);
			pDroppedItem_itemCount.defaultVal = DroppedItem_itemCount_defval;
			pDroppedItemModule.propertys["itemCount"] = pDroppedItem_itemCount; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_itemCount.aliasID] = pDroppedItem_itemCount;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(itemCount / 59).");

			Property pDroppedItem_itemId = new Property();
			pDroppedItem_itemId.name = "itemId";
			pDroppedItem_itemId.properUtype = 58;
			pDroppedItem_itemId.properFlags = 4;
			pDroppedItem_itemId.aliasID = 7;
			Int32 DroppedItem_itemId_defval;
			Int32.TryParse("0", out DroppedItem_itemId_defval);
			pDroppedItem_itemId.defaultVal = DroppedItem_itemId_defval;
			pDroppedItemModule.propertys["itemId"] = pDroppedItem_itemId; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_itemId.aliasID] = pDroppedItem_itemId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(itemId / 58).");

			Property pDroppedItem_modelID = new Property();
			pDroppedItem_modelID.name = "modelID";
			pDroppedItem_modelID.properUtype = 41006;
			pDroppedItem_modelID.properFlags = 4;
			pDroppedItem_modelID.aliasID = 8;
			UInt32 DroppedItem_modelID_defval;
			UInt32.TryParse("0", out DroppedItem_modelID_defval);
			pDroppedItem_modelID.defaultVal = DroppedItem_modelID_defval;
			pDroppedItemModule.propertys["modelID"] = pDroppedItem_modelID; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_modelID.aliasID] = pDroppedItem_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(modelID / 41006).");

			Property pDroppedItem_modelScale = new Property();
			pDroppedItem_modelScale.name = "modelScale";
			pDroppedItem_modelScale.properUtype = 41007;
			pDroppedItem_modelScale.properFlags = 4;
			pDroppedItem_modelScale.aliasID = 9;
			Byte DroppedItem_modelScale_defval;
			Byte.TryParse("30", out DroppedItem_modelScale_defval);
			pDroppedItem_modelScale.defaultVal = DroppedItem_modelScale_defval;
			pDroppedItemModule.propertys["modelScale"] = pDroppedItem_modelScale; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_modelScale.aliasID] = pDroppedItem_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(modelScale / 41007).");

			Property pDroppedItem_name = new Property();
			pDroppedItem_name.name = "name";
			pDroppedItem_name.properUtype = 41003;
			pDroppedItem_name.properFlags = 4;
			pDroppedItem_name.aliasID = 10;
			string DroppedItem_name_defval = "";
			pDroppedItem_name.defaultVal = DroppedItem_name_defval;
			pDroppedItemModule.propertys["name"] = pDroppedItem_name; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_name.aliasID] = pDroppedItem_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(name / 41003).");

			Property pDroppedItem_uid = new Property();
			pDroppedItem_uid.name = "uid";
			pDroppedItem_uid.properUtype = 41004;
			pDroppedItem_uid.properFlags = 4;
			pDroppedItem_uid.aliasID = 11;
			UInt32 DroppedItem_uid_defval;
			UInt32.TryParse("0", out DroppedItem_uid_defval);
			pDroppedItem_uid.defaultVal = DroppedItem_uid_defval;
			pDroppedItemModule.propertys["uid"] = pDroppedItem_uid; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_uid.aliasID] = pDroppedItem_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(uid / 41004).");

			Property pDroppedItem_utype = new Property();
			pDroppedItem_utype.name = "utype";
			pDroppedItem_utype.properUtype = 41005;
			pDroppedItem_utype.properFlags = 4;
			pDroppedItem_utype.aliasID = 12;
			UInt32 DroppedItem_utype_defval;
			UInt32.TryParse("0", out DroppedItem_utype_defval);
			pDroppedItem_utype.defaultVal = DroppedItem_utype_defval;
			pDroppedItemModule.propertys["utype"] = pDroppedItem_utype; 

			pDroppedItemModule.usePropertyDescrAlias = true;
			pDroppedItemModule.idpropertys[(UInt16)pDroppedItem_utype.aliasID] = pDroppedItem_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), property(utype / 41005).");

			List<DATATYPE_BASE> pDroppedItem_pickUpRequest_args = new List<DATATYPE_BASE>();

			Method pDroppedItem_pickUpRequest = new Method();
			pDroppedItem_pickUpRequest.name = "pickUpRequest";
			pDroppedItem_pickUpRequest.methodUtype = 63;
			pDroppedItem_pickUpRequest.aliasID = -1;
			pDroppedItem_pickUpRequest.args = pDroppedItem_pickUpRequest_args;

			pDroppedItemModule.methods["pickUpRequest"] = pDroppedItem_pickUpRequest; 
			pDroppedItemModule.cell_methods["pickUpRequest"] = pDroppedItem_pickUpRequest;

			pDroppedItemModule.idcell_methods[pDroppedItem_pickUpRequest.methodUtype] = pDroppedItem_pickUpRequest;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(DroppedItem), method(pickUpRequest / 63).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ITEM_COUNT";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "AVATAR_INFO";
				DATATYPE_AVATAR_INFO datatype = new DATATYPE_AVATAR_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "AVATAR_INFO_LIST";
				DATATYPE_AVATAR_INFO_LIST datatype = new DATATYPE_AVATAR_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "ITEM_INFO";
				DATATYPE_ITEM_INFO datatype = new DATATYPE_ITEM_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "ITEM_INFO_LIST";
				DATATYPE_ITEM_INFO_LIST datatype = new DATATYPE_ITEM_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "AnonymousArray_30";
				DATATYPE_AnonymousArray_30 datatype = new DATATYPE_AnonymousArray_30();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "AnonymousArray_31";
				DATATYPE_AnonymousArray_31 datatype = new DATATYPE_AnonymousArray_31();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 32;
				string typeName = "AnonymousArray_32";
				DATATYPE_AnonymousArray_32 datatype = new DATATYPE_AnonymousArray_32();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}